name: "CI"
description: "Build & tests program."
runs:
  using: composite
  steps: 
    - name: Download Samuel artifact
      uses: actions/download-artifact@v4
      with:
        name: samuel
    - name: Publish alpha package to Nuget
      shell: pwsh
      run: dotnet nuget push ./nupkg/Samuel.CLI.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

