name: "CI"
description: "Build & tests program."
runs:
  using: composite
  steps: 
    - name: Download Samuel artifact
      uses: actions/download-artifact@v4
      with:
        name: outputs/samuel
# jobs:
#   - job: semantic_release
#     displayName: Semantic Release
#     steps:
#     - checkout: self
#       persistCredentials: true
#       fetchDepth: 0

#     - task: DownloadBuildArtifacts@0
#       displayName: "Download Build Artifact"
#       inputs:
#         buildType: "current"
#         downloadType: "single"
#         artifactName: "SemanticRelease"
#         downloadPath: "$(System.ArtifactsDirectory)/SemanticRelease"

#     - task: Powershell@2
#       displayName: 'Install Samuel'
#       inputs:
#         workingDirectory: "$(System.ArtifactsDirectory)/SemanticRelease/SemanticRelease"
#         targetType: 'inline'
#         pwsh: true
#         script: dotnet tool install --global --add-source . Samuel.Cli
#     - task: Powershell@2
#       displayName: 'Run Samuel'
#       env:
#         Git__Credentials: $(System.AccessToken)
#       inputs:
#         targetType: 'inline'
#         pwsh: true
#         script: |
#             git checkout master
#             git fetch --all
#             git pull
#             samuel run --debug