
name: "CI"
description: "Build & tests program."
runs:
  using: composite
  steps:
  - name: Build
    shell: pwsh
    run: dotnet build --configuration release

  - name: Test
    shell: pwsh
    run: dotnet test --configuration release -- xUnit.AppDomain=denied xUnit.ParallelizeTestCollections=false

  # - name: Performance test
  #   if: github.ref == 'refs/heads/main'
  #   shell: pwsh
  #   run: dotnet run --project Src/Tests/Samuel.Performance.Tests/Samuel.Performance.Tests.csproj --configuration release -- --filter '*ChangelogPerformanceTests*'  --artifacts outputs/performance-test-results

  # - name: Archive performance test results
  #   if: github.ref == 'refs/heads/main'
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: performance-test-results
  #     path: outputs/performance-test-results
  
  - name: Pack
    # if: github.ref == 'refs/heads/main'
    shell: pwsh
    run: dotnet pack Src/Console/Samuel.CLI.csproj --output outputs/samuel

  - name: Archive pack
    # if: github.ref == 'refs/heads/main'
    uses: actions/upload-artifact@v4
    with:
      name: samuel
      path: outputs/samuel