on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: CI
        uses: ./.github/actions/ci
  deploy_alpha_package:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: CD
        with:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          SOURCE: 'https://api.nuget.org/v3/index.json'
        uses: ./.github/actions/cd
  
  # - stage: cd
  #   displayName: CD
  #   jobs:
  #     - template: CD/SemanticRelease.yml
  
    # Publish to nuget