on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: CI
        uses: ./.github/actions/ci
  # - stage: ci
  #   displayName: CI
  #   jobs:
  #     - template: CI/SemanticRelease.yml
  
  # - stage: cd
  #   displayName: CD
  #   jobs:
  #     - template: CD/SemanticRelease.yml
  
    # Publish to nuget