on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: CI
        uses: ./.github/actions/ci
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CD
        uses: ./.github/actions/cd
  
  # - stage: cd
  #   displayName: CD
  #   jobs:
  #     - template: CD/SemanticRelease.yml
  
    # Publish to nuget